# Generated by Django 4.0.4 on 2022-05-17 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('apelido', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('telemovel', models.IntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('morada', models.CharField(max_length=200, null=True)),
                ('cidade', models.CharField(max_length=200, null=True)),
                ('nif', models.IntegerField(null=True)),
                ('precototal', models.FloatField(default=0, null=True)),
                ('pago', models.BooleanField(default=False, null=True)),
                ('emloja', models.BooleanField(default=False, null=True)),
                ('pronto', models.BooleanField(default=False, null=True)),
                ('enviado_ou_levantado', models.BooleanField(default=False, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('fechado', models.BooleanField(default=False)),
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adegadobairro.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Vinho',
            fields=[
                ('vinho_imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('preco', models.FloatField(null=True)),
                ('tipo', models.CharField(choices=[('Tinto', 'Tinto'), ('Branco', 'Branco'), ('Rose', 'Rose'), ('Madeira', 'Madeira'), ('Porto', 'Porto'), ('Frisante', 'Frisante')], max_length=200, null=True)),
                ('regiao', models.CharField(choices=[('Alentejo', 'Alentejo'), ('Algarve', 'Algarve'), ('Bairrada', 'Bairrada'), ('Beira Atlântico', 'Beira Atlântico'), ('Beira Interior', 'Beira Interior'), ('Dão', 'Dão'), ('Douro', 'Douro'), ('Lisboa', 'Lisboa'), ('Madeira', 'Madeira'), ('Minho', 'Minho'), ('Setúbal', 'Setúbal'), ('Távora-varosa', 'Távora-varosa'), ('Tejo', 'Tejo'), ('Trás-os-Montes', 'Trás-os-Montes'), ('Verdes', 'Verdes')], max_length=200, null=True)),
                ('colheita', models.IntegerField(null=True)),
                ('produtor', models.CharField(max_length=200, null=True)),
                ('precopromocao', models.FloatField(default=0, null=True)),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('datainsercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('vendas', models.IntegerField(default=0, null=True)),
                ('precoatual', models.FloatField(default=0, null=True)),
                ('vinho_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Vinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField(null=True)),
                ('quantidade', models.IntegerField(default=0, null=True)),
                ('precototal', models.FloatField(default=0, null=True)),
                ('fechado', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adegadobairro.pedido')),
                ('vinho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adegadobairro.vinho')),
            ],
        ),
    ]
